name = mcl_end_portal_bucket
title = End Portal Buckets for Mineclonia
description = Adds an easy way to carry the end portal where ever you go in Mineclonia.
depends = mcl_buckets
supported_games = mineclone2
unsupported_games = mineclone5
min_minetest_version = 5.10